### ISSUE TITLE
Add documentation on GNSS-A Technique used

### ISSUE THREAD

**Issue by lsetiawan** [seafloor-geodesy/gnatss#145]
Reference slides by John DeSanto: https://drive.google.com/file/d/1vKl4Q_RJ2BurLHSOYxBR5aFfqen1B4vh/view?pli=1

**Comment by lsetiawan** [comment]
@johnbdesanto Here's a nice guide to get started with Markdown and Latex: https://ashki23.github.io/markdown-latex.html

**Comment by lsetiawan** [comment]
Please add this to your `conf.yml`

```yaml
parse:
  myst_enable_extensions:
  - amsmath
  - dollarmath
```
