### ISSUE TITLE
Install and test out the software 

### ISSUE THREAD

**Issue by lsetiawan** [seafloor-geodesy/gnatss#175]
## Overview

@johnbdesanto will be testing the software on a dataset that he has

## Instructions

0. Create a new conda environment and activate

    ```console
    conda create -n gnatss -c conda-forge --yes python=3.10 ipykernel
    conda activate gnatss
    ```

1. Install the current version in test pypi:

    ```console
    pip install --extra-index-url https://test.pypi.org/simple/ gnatss
    ```

2. Create config.yaml file in working directory

    ```yaml
    site_id: Site Name

    solver:
      transponders: # list out all transponder and info
        - lat: 45.302064471
          lon: -124.978181346
          height: -1176.5866
          internal_delay: 0.200000
          sv_mean: 1481.551
        - lat: 45.295207747
          lon: -124.958752845
          height: -1146.5881
          internal_delay: 0.320000
          sv_mean: 1481.521
        - lat: 45.309643593
          lon: -124.959348875
          height: -1133.7305
          internal_delay: 0.440000
          sv_mean: 1481.509
      reference_ellipsoid:
        semi_major_axis: 6378137.000
        reverse_flattening: 298.257222101
      gps_sigma_limit: 0.05
      std_dev: true
      geoid_undulation: -26.59
      bisection_tolerance: 1e-10
      array_center:
        lat: 45.3023
        lon: -124.9656
      travel_times_variance: 1e-10
      travel_times_correction: 0.0
      transducer_delay_time: 0.0
      harmonic_mean_start_depth: -4.0
      input_files:
        sound_speed:
          path: ./tests/data/2022/NCL1/ctd/CTD_NCL1_Ch_Mi
        travel_times: # Glob path to pxp_tt
          path: ./tests/data/2022/NCL1/**/WG_*/pxp_tt
        gps_solution:  # Glob path to POS_FREED_TRANS_TWTT
          path: ./tests/data/2022/NCL1/**/posfilter/POS_FREED_TRANS_TWTT
    
    
    output: # Directory path to output directory
      path: ./tests/data/output/
    ```

3. Run the gnatss solver routine in the same directory as the `config.yaml` file

    ```console
    gnatss run --extract-dist-center --extract-process-dataset --qc --distance-limit 150 --residual-limit 10000
    ```
