### ISSUE TITLE
feat: Add `atd_offset` to posfilter config model

### ISSUE THREAD

**Issue by lsetiawan** [seafloor-geodesy/gnatss#211]
Config with posfilter should be like so:

```
posfilter:
  atd_offsets:
    forward: 0.0053
    right: 0
    down: 0.92813
  input_files:
    roll_pitch_heading:
      path: path_to_rph/**/RPH_FILE
```
